[package]
name = "assertion"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = ["once_cell"]

[dependencies]
once_cell = { version = "1.13.0", optional = true }
