[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "dsl_parser"
repository.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
chumsky = "0.10.1"
rusqlite = { workspace = true }
