[env]
LIBSQLITE3_FLAGS = "-DSQLITE_ENABLE_MATH_FUNCTIONS" # necessary for rusqlite dependency in order to bundle SQLite with math functions included
CARGO_WORKSPACE_DIR = { value = "", relative = true } # neccessary for generate script to reliably get the root workspace directory
